### ISSUE TITLE
Is TOTG planning adapter for only joint velocities and joint-accelration constraints?

### ISSUE THREAD

**Issue by lakshmip001** [tud-cor/moveit_totg_planning_adapter#2]
I need to constraint tool velocity of the robot to get a trapezoidal velocity for the manipulator. Can I use for Cartesian velocity and Cartesian acceleration constraints?

**Comment by gavanderhoorn** [comment]
The way the adapter is currently implemented it will only use the TOTG algorithm for deriving joint space timing data, yes.

Whether the algorithm could be used for other purposes I'm not sure, I would have to check the paper again.

**Comment by gavanderhoorn** [comment]
As this is more a question than an actionable issue, I'm closing this.

Feel free to keep commenting on it though.
